redis:
  host: tdw01.dev01.in.tdw
  port: 6379
  password: t4d4r3d1s
  database: 1
  default: 50

rabbitmq:
  host: tdw01.dev01.in.tdw
  port: 5672
  vhost: hapiness_antoine
  login: tadaweb
  password: tadaweb
